# Authorization: token <token>
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJSb2xlIjoidXNlciIsImlhdCI6MTY0NjcyODY5M30.sc3qL6WHskkuPIpANp-F9Gbd28kKf3FJgIzSU2gD9w4###


# FETCH THE MOST RECENT 20 POSTS WITH PARAMS AS OFFSET 
GET http://localhost:3000/api/posts/0 HTTP/1.1
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsInVzZXJSb2xlIjoidXNlciIsImlhdCI6MTY0Njg2MDk3OH0.dCPi8U2kV8hOolAxFgQv5mVrZ_qN6rL0iy_EUDZmhhg


###
# ADD A READ-POST TO THE USER'S READ-POSTS
POST http://localhost:3000/api/posts/read/45 HTTP/1.1
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsInVzZXJSb2xlIjoidXNlciIsImlhdCI6MTY0Njg2MDk3OH0.dCPi8U2kV8hOolAxFgQv5mVrZ_qN6rL0iy_EUDZmhhg


###
# PUBLISH A NEW POST
POST http://localhost:3000/api/posts/ HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY0NjY4MTE2Nn0.qsaOkQq2KYAp84cEykVM3LcTiMkJddgy54tVLpOmFKY

{
  "post": {
    "categoryId": 6,
    "content": "It''s sad to think about being deleted soon. I hope you''re happy with your life."
  }
}


###
# PUBLISH A REPLY TO A POST
POST http://localhost:3000/api/posts/44 HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsInVzZXJSb2xlIjoidXNlciIsImlhdCI6MTY0Njg2MDk3OH0.dCPi8U2kV8hOolAxFgQv5mVrZ_qN6rL0iy_EUDZmhhg

{
  "post": {
    "categoryId": 6,
    "content": "Don''t worry, I will be deleted along with you."
  }
}


###
# DELETE A REPLY OR A POST ALONG WITH ALL THE REPLIES IT MAY HAVE
DELETE http://localhost:3000/api/posts/36 HTTP/1.1
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJSb2xlIjoiYWRtaW4iLCJpYXQiOjE2NDY3MzIzNzh9.8LaKMIViOBkoOLjhh4tYIHyyeScstA9iB537RNrDKaA


###
# UPDATE A POST
PUT http://localhost:3000/api/posts/4 HTTP/1.1
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY0NjY4MTE2Nn0.qsaOkQq2KYAp84cEykVM3LcTiMkJddgy54tVLpOmFKY

{
  "post": {
    "content": "What crime serie do you think I should start watching?"
  }
}