# Authorization: token <token>
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY0NjY4MTE2Nn0.qsaOkQq2KYAp84cEykVM3LcTiMkJddgy54tVLpOmFKY


###
# LIST EMAILS AND NICKNAMES
GET http://localhost:3000/api/auth/emails-and-nicknames HTTP/1.1


###
# GET A USER
GET http://localhost:3000/api/auth/1 HTTP/1.1


###
# GET USER INFOS FROM TOKEN
POST http://localhost:3000/api/auth/own HTTP/1.1
content-type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJSb2xlIjoiYWRtaW4iLCJpYXQiOjE2NDcyNjQzODR9.nbPPsIvJ0tFEwI3z3PFHs6ReqZ0C4R-4EEcP29GEgY0"
}


###
# REGISTER NEW USER
POST http://localhost:3000/api/auth/signup HTTP/1.1
content-type: application/json

{
  "email": "test2@test2.com",
  "nickname": "test2",
  "password": "123"
}


###
# LOGIN THE USER
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
  "email": "colleague@happy.com",
  "password": "123"
}


###
# LOGIN THE USER WITH ERROR
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
  "email": "colleaguez@happy.com",
  "password": "1234"
}


###
# DELETE USER
DELETE http://localhost:3000/api/auth/1 HTTP/1.1
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJSb2xlIjoiYWRtaW4iLCJpYXQiOjE2NDcwMDMwNDl9.gq8GuWjR3oK1UVZJCRrFW8-RgwWOL1i5OtrsRWVh_3s
